In [69]:
# Importing necessary packages

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
#!pip install pdftables.six
from pdftables import get_tables

In [70]:
# opening the pdf file and using get_tables function
# The get_tables() function returns the page as its own table
# The tables have a list of rows, and each of those row is a contained list of columns

pdf_file = 'council_suburb.pdf'
pdf_obj = open(pdf_file, 'rb')
tables = get_tables(pdf_obj)

In [71]:
# print out each row in table
# creating a DataFrame by passing a dictionary of objects

df = {}
for table in tables:
    for row in table[5:]:
        df[row[0]] = row[1:]
        print (row)

df = pd.DataFrame(df)
df

['1', '1', 'Monash (C)', 'Glen Waverley, Clayton, Mount Waverley, Wheelers Hill, Mulgrave (Vic.)']
['2', '3', 'Melbourne (C)', 'Melbourne, Carlton (Vic.), Southbank, North Melbourne, Docklands']
['3', '2', 'Whitehorse (C)', 'Box Hill (Vic.), Burwood (Vic.), Box Hill North, Burwood East, Vermont South']
['4', '4', 'Boroondara (C)', 'Balwyn North, Balwyn, Kew (Vic.), Camberwell (Vic.), Hawthorn (Vic.)']
['5', '5', 'Manningham (C)', 'Doncaster East, Doncaster, Templestowe, Templestowe Lower, Bulleen']
['6', '7', 'Glen Eira (C)', 'Carnegie, Bentleigh East, Bentleigh, Murrumbeena, Ormond']
['7', '9', 'Knox (C)', 'Wantirna South, Rowville, Wantirna, Boronia, Bayswater (Vic.)']
['8', '12', 'Wyndham (C)', 'Point Cook, Truganina, Williams Landing, Hoppers Crossing, Tarneit']
['9', '6', 'Darebin (C)', 'Reservoir (Vic.), Preston (Vic.), Bundoora (Vic.), Kingsbury, Northcote']
['10', '8', 'Greater Dandenong (C)', 'Springvale (Vic.), Keysborough, Dandenong, Noble Park, Dandenong North']
['11', '13', 'Stonnington (C)', 'Malvern East, South Yarra, Toorak, Glen Iris (Vic.), Malvern (Vic.)']
['12', '11', 'Casey (C)', 'Berwick, Endeavour Hills, Narre Warren, Hampton Park, Narre Warren South']
['13', '10', 'Kingston (C)', 'Clayton South, Cheltenham (Vic.), Mentone, Moorabbin, Clarinda']
['14', '18', 'Whittlesea (C)', 'Bundoora (Vic.), Mill Park, Epping (Vic.), Thomastown, Lalor']
['15', '14', 'Banyule (C)', 'Bundoora (Vic.), Ivanhoe (Vic.), Viewbank, Greensborough, Macleod (Vic.)']
['16', '19', 'Maroondah (C)', 'Ringwood (Vic.), Croydon (Vic.), Ringwood East, Ringwood North, Heathmont']
['17', '15', 'Moreland (C)', 'Brunswick (Vic.), Coburg, Glenroy (Vic.), Brunswick West, Pascoe Vale']
['18', '17', 'Brimbank (C)', 'St Albans (Vic.), Deer Park, Sunshine West, Sunshine (Vic.), Cairnlea']
['19', '16', 'Maribyrnong (C)', 'Maribyrnong, Footscray, Maidstone, Braybrook, West Footscray']
['20', '20', 'Moonee Valley (C)', 'Travancore, Essendon, Ascot Vale, Moonee Ponds, Avondale Heights']

,1,10,11,12,13,14,15,16,17,18,19,2,20,3,4,5,6,7,8,9
0,1,8,13,11,10,18,14,19,15,17,16,3,20,2,4,5,7,9,12,6
1,Monash (C),Greater Dandenong (C),Stonnington (C),Casey (C),Kingston (C),Whittlesea (C),Banyule (C),Maroondah (C),Moreland (C),Brimbank (C),Maribyrnong (C),Melbourne (C),Moonee Valley (C),Whitehorse (C),Boroondara (C),Manningham (C),Glen Eira (C),Knox (C),Wyndham (C),Darebin (C)
2,"Glen Waverley, Clayton, Mount Waverley, Wheele...","Springvale (Vic.), Keysborough, Dandenong, Nob...","Malvern East, South Yarra, Toorak, Glen Iris (...","Berwick, Endeavour Hills, Narre Warren, Hampto...","Clayton South, Cheltenham (Vic.), Mentone, Moo...","Bundoora (Vic.), Mill Park, Epping (Vic.), Tho...","Bundoora (Vic.), Ivanhoe (Vic.), Viewbank, Gre...","Ringwood (Vic.), Croydon (Vic.), Ringwood East...","Brunswick (Vic.), Coburg, Glenroy (Vic.), Brun...","St Albans (Vic.), Deer Park, Sunshine West, Su...","Maribyrnong, Footscray, Maidstone, Braybrook, ...","Melbourne, Carlton (Vic.), Southbank, North Me...","Travancore, Essendon, Ascot Vale, Moonee Ponds...","Box Hill (Vic.), Burwood (Vic.), Box Hill Nort...","Balwyn North, Balwyn, Kew (Vic.), Camberwell (...","Doncaster East, Doncaster, Templestowe, Temple...","Carnegie, Bentleigh East, Bentleigh, Murrumbee...","Wantirna South, Rowville, Wantirna, Boronia, B...","Point Cook, Truganina, Williams Landing, Hoppe...","Reservoir (Vic.), Preston (Vic.), Bundoora (Vi..."

In [72]:
# The last step is to transpose the DataFrame so that each row is a record for a council
# save the data into a CSV file

df = df.T
df.columns = range(3)
df.to_csv('council_suburb.csv')

In [73]:
#Loading the language csv 

df = pd.read_csv('council_suburb.csv')
df

,Unnamed: 0,0,1,2
0,1,1,Monash (C),"Glen Waverley, Clayton, Mount Waverley, Wheele..."
1,10,8,Greater Dandenong (C),"Springvale (Vic.), Keysborough, Dandenong, Nob..."
2,11,13,Stonnington (C),"Malvern East, South Yarra, Toorak, Glen Iris (..."
3,12,11,Casey (C),"Berwick, Endeavour Hills, Narre Warren, Hampto..."
4,13,10,Kingston (C),"Clayton South, Cheltenham (Vic.), Mentone, Moo..."
5,14,18,Whittlesea (C),"Bundoora (Vic.), Mill Park, Epping (Vic.), Tho..."
6,15,14,Banyule (C),"Bundoora (Vic.), Ivanhoe (Vic.), Viewbank, Gre..."
7,16,19,Maroondah (C),"Ringwood (Vic.), Croydon (Vic.), Ringwood East..."
8,17,15,Moreland (C),"Brunswick (Vic.), Coburg, Glenroy (Vic.), Brun..."
9,18,17,Brimbank (C),"St Albans (Vic.), Deer Park, Sunshine West, Su..."
10,19,16,Maribyrnong (C),"Maribyrnong, Footscray, Maidstone, Braybrook, ..."
11,2,3,Melbourne (C),"Melbourne, Carlton (Vic.), Southbank, North Me..."
12,20,20,Moonee Valley (C),"Travancore, Essendon, Ascot Vale, Moonee Ponds..."
13,3,2,Whitehorse (C),"Box Hill (Vic.), Burwood (Vic.), Box Hill Nort..."
14,4,4,Boroondara (C),"Balwyn North, Balwyn, Kew (Vic.), Camberwell (..."
15,5,5,Manningham (C),"Doncaster East, Doncaster, Templestowe, Temple..."
16,6,7,Glen Eira (C),"Carnegie, Bentleigh East, Bentleigh, Murrumbee..."
17,7,9,Knox (C),"Wantirna South, Rowville, Wantirna, Boronia, B..."
18,8,12,Wyndham (C),"Point Cook, Truganina, Williams Landing, Hoppe..."
19,9,6,Darebin (C),"Reservoir (Vic.), Preston (Vic.), Bundoora (Vi..."

In [74]:
#Renaming columns

df.columns = ['Rank 2016', 'Rank 2011', 'LGA name', 'Suburbs']
df

,Rank 2016,Rank 2011,LGA name,Suburbs
0,1,1,Monash (C),"Glen Waverley, Clayton, Mount Waverley, Wheele..."
1,10,8,Greater Dandenong (C),"Springvale (Vic.), Keysborough, Dandenong, Nob..."
2,11,13,Stonnington (C),"Malvern East, South Yarra, Toorak, Glen Iris (..."
3,12,11,Casey (C),"Berwick, Endeavour Hills, Narre Warren, Hampto..."
4,13,10,Kingston (C),"Clayton South, Cheltenham (Vic.), Mentone, Moo..."
5,14,18,Whittlesea (C),"Bundoora (Vic.), Mill Park, Epping (Vic.), Tho..."
6,15,14,Banyule (C),"Bundoora (Vic.), Ivanhoe (Vic.), Viewbank, Gre..."
7,16,19,Maroondah (C),"Ringwood (Vic.), Croydon (Vic.), Ringwood East..."
8,17,15,Moreland (C),"Brunswick (Vic.), Coburg, Glenroy (Vic.), Brun..."
9,18,17,Brimbank (C),"St Albans (Vic.), Deer Park, Sunshine West, Su..."
10,19,16,Maribyrnong (C),"Maribyrnong, Footscray, Maidstone, Braybrook, ..."
11,2,3,Melbourne (C),"Melbourne, Carlton (Vic.), Southbank, North Me..."
12,20,20,Moonee Valley (C),"Travancore, Essendon, Ascot Vale, Moonee Ponds..."
13,3,2,Whitehorse (C),"Box Hill (Vic.), Burwood (Vic.), Box Hill Nort..."
14,4,4,Boroondara (C),"Balwyn North, Balwyn, Kew (Vic.), Camberwell (..."
15,5,5,Manningham (C),"Doncaster East, Doncaster, Templestowe, Temple..."
16,6,7,Glen Eira (C),"Carnegie, Bentleigh East, Bentleigh, Murrumbee..."
17,7,9,Knox (C),"Wantirna South, Rowville, Wantirna, Boronia, B..."
18,8,12,Wyndham (C),"Point Cook, Truganina, Williams Landing, Hoppe..."
19,9,6,Darebin (C),"Reservoir (Vic.), Preston (Vic.), Bundoora (Vi..."

In [75]:
# stripping "(C)" from the LGA name column

df['LGA name']=df['LGA name'].str.replace(r"\(.*\)","")
df

,Rank 2016,Rank 2011,LGA name,Suburbs
0,1,1,Monash,"Glen Waverley, Clayton, Mount Waverley, Wheele..."
1,10,8,Greater Dandenong,"Springvale (Vic.), Keysborough, Dandenong, Nob..."
2,11,13,Stonnington,"Malvern East, South Yarra, Toorak, Glen Iris (..."
3,12,11,Casey,"Berwick, Endeavour Hills, Narre Warren, Hampto..."
4,13,10,Kingston,"Clayton South, Cheltenham (Vic.), Mentone, Moo..."
5,14,18,Whittlesea,"Bundoora (Vic.), Mill Park, Epping (Vic.), Tho..."
6,15,14,Banyule,"Bundoora (Vic.), Ivanhoe (Vic.), Viewbank, Gre..."
7,16,19,Maroondah,"Ringwood (Vic.), Croydon (Vic.), Ringwood East..."
8,17,15,Moreland,"Brunswick (Vic.), Coburg, Glenroy (Vic.), Brun..."
9,18,17,Brimbank,"St Albans (Vic.), Deer Park, Sunshine West, Su..."
10,19,16,Maribyrnong,"Maribyrnong, Footscray, Maidstone, Braybrook, ..."
11,2,3,Melbourne,"Melbourne, Carlton (Vic.), Southbank, North Me..."
12,20,20,Moonee Valley,"Travancore, Essendon, Ascot Vale, Moonee Ponds..."
13,3,2,Whitehorse,"Box Hill (Vic.), Burwood (Vic.), Box Hill Nort..."
14,4,4,Boroondara,"Balwyn North, Balwyn, Kew (Vic.), Camberwell (..."
15,5,5,Manningham,"Doncaster East, Doncaster, Templestowe, Temple..."
16,6,7,Glen Eira,"Carnegie, Bentleigh East, Bentleigh, Murrumbee..."
17,7,9,Knox,"Wantirna South, Rowville, Wantirna, Boronia, B..."
18,8,12,Wyndham,"Point Cook, Truganina, Williams Landing, Hoppe..."
19,9,6,Darebin,"Reservoir (Vic.), Preston (Vic.), Bundoora (Vi..."

In [76]:
df['Suburbs']=df['Suburbs'].str.replace("(Vic.)","")
df

,Rank 2016,Rank 2011,LGA name,Suburbs
0,1,1,Monash,"Glen Waverley, Clayton, Mount Waverley, Wheele..."
1,10,8,Greater Dandenong,"Springvale (), Keysborough, Dandenong, Noble P..."
2,11,13,Stonnington,"Malvern East, South Yarra, Toorak, Glen Iris (..."
3,12,11,Casey,"Berwick, Endeavour Hills, Narre Warren, Hampto..."
4,13,10,Kingston,"Clayton South, Cheltenham (), Mentone, Moorabb..."
5,14,18,Whittlesea,"Bundoora (), Mill Park, Epping (), Thomastown,..."
6,15,14,Banyule,"Bundoora (), Ivanhoe (), Viewbank, Greensborou..."
7,16,19,Maroondah,"Ringwood (), Croydon (), Ringwood East, Ringwo..."
8,17,15,Moreland,"Brunswick (), Coburg, Glenroy (), Brunswick We..."
9,18,17,Brimbank,"St Albans (), Deer Park, Sunshine West, Sunshi..."
10,19,16,Maribyrnong,"Maribyrnong, Footscray, Maidstone, Braybrook, ..."
11,2,3,Melbourne,"Melbourne, Carlton (), Southbank, North Melbou..."
12,20,20,Moonee Valley,"Travancore, Essendon, Ascot Vale, Moonee Ponds..."
13,3,2,Whitehorse,"Box Hill (), Burwood (), Box Hill North, Burwo..."
14,4,4,Boroondara,"Balwyn North, Balwyn, Kew (), Camberwell (), H..."
15,5,5,Manningham,"Doncaster East, Doncaster, Templestowe, Temple..."
16,6,7,Glen Eira,"Carnegie, Bentleigh East, Bentleigh, Murrumbee..."
17,7,9,Knox,"Wantirna South, Rowville, Wantirna, Boronia, B..."
18,8,12,Wyndham,"Point Cook, Truganina, Williams Landing, Hoppe..."
19,9,6,Darebin,"Reservoir (), Preston (), Bundoora (), Kingsbu..."

In [77]:
# sort the dataframe in descending order based on the values of below three columns

df=df.sort_values('Rank 2016')
df

,Rank 2016,Rank 2011,LGA name,Suburbs
0,1,1,Monash,"Glen Waverley, Clayton, Mount Waverley, Wheele..."
11,2,3,Melbourne,"Melbourne, Carlton (), Southbank, North Melbou..."
13,3,2,Whitehorse,"Box Hill (), Burwood (), Box Hill North, Burwo..."
14,4,4,Boroondara,"Balwyn North, Balwyn, Kew (), Camberwell (), H..."
15,5,5,Manningham,"Doncaster East, Doncaster, Templestowe, Temple..."
16,6,7,Glen Eira,"Carnegie, Bentleigh East, Bentleigh, Murrumbee..."
17,7,9,Knox,"Wantirna South, Rowville, Wantirna, Boronia, B..."
18,8,12,Wyndham,"Point Cook, Truganina, Williams Landing, Hoppe..."
19,9,6,Darebin,"Reservoir (), Preston (), Bundoora (), Kingsbu..."
1,10,8,Greater Dandenong,"Springvale (), Keysborough, Dandenong, Noble P..."
2,11,13,Stonnington,"Malvern East, South Yarra, Toorak, Glen Iris (..."
3,12,11,Casey,"Berwick, Endeavour Hills, Narre Warren, Hampto..."
4,13,10,Kingston,"Clayton South, Cheltenham (), Mentone, Moorabb..."
5,14,18,Whittlesea,"Bundoora (), Mill Park, Epping (), Thomastown,..."
6,15,14,Banyule,"Bundoora (), Ivanhoe (), Viewbank, Greensborou..."
7,16,19,Maroondah,"Ringwood (), Croydon (), Ringwood East, Ringwo..."
8,17,15,Moreland,"Brunswick (), Coburg, Glenroy (), Brunswick We..."
9,18,17,Brimbank,"St Albans (), Deer Park, Sunshine West, Sunshi..."
10,19,16,Maribyrnong,"Maribyrnong, Footscray, Maidstone, Braybrook, ..."
12,20,20,Moonee Valley,"Travancore, Essendon, Ascot Vale, Moonee Ponds..."

In [78]:
# dropping columns
df = df.drop(['Rank 2016', 'Rank 2011'], axis=1)
df

              LGA name                                            Suburbs
0              Monash   Glen Waverley, Clayton, Mount Waverley, Wheele...
11          Melbourne   Melbourne, Carlton (), Southbank, North Melbou...
13         Whitehorse   Box Hill (), Burwood (), Box Hill North, Burwo...
14         Boroondara   Balwyn North, Balwyn, Kew (), Camberwell (), H...
15         Manningham   Doncaster East, Doncaster, Templestowe, Temple...
16          Glen Eira   Carnegie, Bentleigh East, Bentleigh, Murrumbee...
17               Knox   Wantirna South, Rowville, Wantirna, Boronia, B...
18            Wyndham   Point Cook, Truganina, Williams Landing, Hoppe...
19            Darebin   Reservoir (), Preston (), Bundoora (), Kingsbu...
1   Greater Dandenong   Springvale (), Keysborough, Dandenong, Noble P...
2         Stonnington   Malvern East, South Yarra, Toorak, Glen Iris (...
3               Casey   Berwick, Endeavour Hills, Narre Warren, Hampto...
4            Kingston   Clayton South, Cheltenham (), Mentone, Moorabb...
5          Whittlesea   Bundoora (), Mill Park, Epping (), Thomastown,...
6             Banyule   Bundoora (), Ivanhoe (), Viewbank, Greensborou...
7           Maroondah   Ringwood (), Croydon (), Ringwood East, Ringwo...
8            Moreland   Brunswick (), Coburg, Glenroy (), Brunswick We...
9            Brimbank   St Albans (), Deer Park, Sunshine West, Sunshi...
10        Maribyrnong   Maribyrnong, Footscray, Maidstone, Braybrook, ...
12      Moonee Valley   Travancore, Essendon, Ascot Vale, Moonee Ponds...

In [79]:
# checking the datatype of column
df['Suburbs'].dtype

dtype('O')

In [80]:
#Exporting to csv file
df.to_csv('council_suburb_chinese.csv',index = False)